// <auto-generated />
using System;
using Kariyer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kariyer.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240930082834_UpdateForeign")]
    partial class UpdateForeign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kariyer.Entities.Basvuran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Basvuranlar");
                });

            modelBuilder.Entity("Kariyer.Entities.Bolum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("FakulteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FakulteId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("Kariyer.Entities.CalismaSekli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("CalismaSekilleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Cinsiyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Cinsiyetler");
                });

            modelBuilder.Entity("Kariyer.Entities.DeneyimSure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("DeneyimSureleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Egitim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BolumId");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Egitimler");
                });

            modelBuilder.Entity("Kariyer.Entities.EkBilgi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bilgiler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("EkBilgiler");
                });

            modelBuilder.Entity("Kariyer.Entities.Fakulte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UniversiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversiteId");

                    b.ToTable("Fakulteler");
                });

            modelBuilder.Entity("Kariyer.Entities.FavoriIlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("UyelikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("UyelikId");

                    b.ToTable("FavoriIlanlar");
                });

            modelBuilder.Entity("Kariyer.Entities.Hakkimda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("CalismaSekli")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DeneyimYili")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Konum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Meslek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MezuniyetDerecesi")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Hakkimda");
                });

            modelBuilder.Entity("Kariyer.Entities.Hobi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Hobiler");
                });

            modelBuilder.Entity("Kariyer.Entities.Ilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("IlanTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsTanimi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PozisyonAdi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SirketImkanlari")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("SonBasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tercihen")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Yetkinlikler")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Ilanlar");
                });

            modelBuilder.Entity("Kariyer.Entities.IlanDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("IlanDurumlari");
                });

            modelBuilder.Entity("Kariyer.Entities.IlanKayit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("UyelikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("UyelikId");

                    b.ToTable("IlanKayitlari");
                });

            modelBuilder.Entity("Kariyer.Entities.IsDeneyim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Adi")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<string>("SirketAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("IsDeneyimleri");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniCalismaSekli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalismaSekliId")
                        .HasColumnType("int");

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalismaSekliId");

                    b.HasIndex("IlanId");

                    b.ToTable("IsIlaniCalismaSekilleri");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniCinsiyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CinsiyetId")
                        .HasColumnType("int");

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("IlanId");

                    b.ToTable("IsIlaniCinsiyetler");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniDeneyimSuresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeneyimSureId")
                        .HasColumnType("int");

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeneyimSureId");

                    b.HasIndex("IlanId");

                    b.ToTable("IsIlaniDeneyimSureleri");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanDurumId")
                        .HasColumnType("int");

                    b.Property<int?>("IlanDurumuId")
                        .HasColumnType("int");

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanDurumuId");

                    b.HasIndex("IlanId");

                    b.ToTable("IsIlaniDurumlari");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniMezuniyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("MezuniyetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("MezuniyetId");

                    b.ToTable("IsIlaniMezuniyetleri");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniSehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("SehirId");

                    b.ToTable("IsIlaniSehirler");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniSektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("SektorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("SektorId");

                    b.ToTable("IsIlaniSektorler");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniUlke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("UlkeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("UlkeId");

                    b.ToTable("IsIlaniUlkeler");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniYabanciDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<string>("Konusma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Okuma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YabanciDilId")
                        .HasColumnType("int");

                    b.Property<string>("Yazma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("YabanciDilId");

                    b.ToTable("IlaniYabanciDilleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Mezuniyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Mezuniyetler");
                });

            modelBuilder.Entity("Kariyer.Entities.Mulakat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Mulakatlar");
                });

            modelBuilder.Entity("Kariyer.Entities.MulakatListe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("MulakatId")
                        .HasColumnType("int");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("MulakatId");

                    b.HasIndex("OzgecmisId");

                    b.HasIndex("SirketId");

                    b.ToTable("MulakatListeleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Ozgecmis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CinsiyetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UlkeId")
                        .HasColumnType("int");

                    b.Property<int>("UyelikId")
                        .HasColumnType("int");

                    b.Property<int>("UyrukId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CinsiyetId");

                    b.HasIndex("UlkeId");

                    b.HasIndex("UyelikId");

                    b.ToTable("Ozgecmisler");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisHavuzu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.HasIndex("SirketId");

                    b.ToTable("OzgecmisHavuzlari");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisSehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.HasIndex("SehirId");

                    b.ToTable("OzgecmisSehirleri");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisSosyalMedya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HesapAdi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<int>("SosyalMedyaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.HasIndex("SosyalMedyaId");

                    b.ToTable("OzgecmisSosyalMedyalar");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisYabanciDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Konusma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Okuma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<int>("YabanciDilId")
                        .HasColumnType("int");

                    b.Property<string>("Yazma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.HasIndex("YabanciDilId");

                    b.ToTable("OzgecmisYabanciDiller");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisYazilimDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("BilgiOrani")
                        .HasColumnType("tinyint");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<int>("YazilimDilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.HasIndex("YazilimDilId");

                    b.ToTable("OzgecmisYazilimDiller");
                });

            modelBuilder.Entity("Kariyer.Entities.Referans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<string>("RefAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SirketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Referanlar");
                });

            modelBuilder.Entity("Kariyer.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RolAdi = "Admin"
                        });
                });

            modelBuilder.Entity("Kariyer.Entities.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("Kariyer.Entities.Sektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Sektorler");
                });

            modelBuilder.Entity("Kariyer.Entities.Sertifika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("KurumAdi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Sertifikalar");
                });

            modelBuilder.Entity("Kariyer.Entities.Sinav", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("OzgecmisId")
                        .HasColumnType("int");

                    b.Property<string>("Puan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OzgecmisId");

                    b.ToTable("Sinavlar");
                });

            modelBuilder.Entity("Kariyer.Entities.Sirket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Hakkimizda")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Link")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelefonNo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UyelikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyelikId");

                    b.ToTable("Sirketler");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketIlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("SirketId");

                    b.ToTable("SirketIlanlari");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketSehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SehirId");

                    b.HasIndex("SirketId");

                    b.ToTable("SirketSehirleri");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketSektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SektorId")
                        .HasColumnType("int");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SektorId");

                    b.HasIndex("SirketId");

                    b.ToTable("SirketSektorleri");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketSosyalMedya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HesapAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.Property<int>("SosyalMedyaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.HasIndex("SosyalMedyaId");

                    b.ToTable("SirketSosyalMedyalar");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SirketId")
                        .HasColumnType("int");

                    b.Property<int>("UyelikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SirketId");

                    b.HasIndex("UyelikId");

                    b.ToTable("SirketTakipleri");
                });

            modelBuilder.Entity("Kariyer.Entities.SosyalMedya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SosyalMedyalar");
                });

            modelBuilder.Entity("Kariyer.Entities.Ulke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Ulkeler");
                });

            modelBuilder.Entity("Kariyer.Entities.Universite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Universiteler");
                });

            modelBuilder.Entity("Kariyer.Entities.Uyelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Uyelikler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adi = "Admin",
                            Email = "admin@kariyer.tc",
                            KayitTarihi = new DateTime(2024, 9, 30, 11, 28, 34, 201, DateTimeKind.Local).AddTicks(9504),
                            KullaniciAdi = "Admin",
                            RolId = 1,
                            Sifre = "123456",
                            Soyadi = "ADMİN",
                            UserGuid = new Guid("abf19994-b831-4f75-ac88-16c6c035518d")
                        });
                });

            modelBuilder.Entity("Kariyer.Entities.YabanciDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("YabanciDiller");
                });

            modelBuilder.Entity("Kariyer.Entities.YazilimDil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("YazilimDiller");
                });

            modelBuilder.Entity("Kariyer.Entities.Basvuran", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.Bolum", b =>
                {
                    b.HasOne("Kariyer.Entities.Fakulte", null)
                        .WithMany("Bolumler")
                        .HasForeignKey("FakulteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.Egitim", b =>
                {
                    b.HasOne("Kariyer.Entities.Bolum", null)
                        .WithMany("Egitimler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ozgecmis", null)
                        .WithMany("Egitim")
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.EkBilgi", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.Fakulte", b =>
                {
                    b.HasOne("Kariyer.Entities.Universite", null)
                        .WithMany("Fakulteler")
                        .HasForeignKey("UniversiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.FavoriIlan", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Uyelik", "Uyelik")
                        .WithMany()
                        .HasForeignKey("UyelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Uyelik");
                });

            modelBuilder.Entity("Kariyer.Entities.Hakkimda", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.Hobi", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.IlanKayit", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Uyelik", "Uyelik")
                        .WithMany()
                        .HasForeignKey("UyelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Uyelik");
                });

            modelBuilder.Entity("Kariyer.Entities.IsDeneyim", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniCalismaSekli", b =>
                {
                    b.HasOne("Kariyer.Entities.CalismaSekli", "CalismaSekli")
                        .WithMany()
                        .HasForeignKey("CalismaSekliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalismaSekli");

                    b.Navigation("Ilan");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniCinsiyet", b =>
                {
                    b.HasOne("Kariyer.Entities.Cinsiyet", "Cinsiyet")
                        .WithMany()
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinsiyet");

                    b.Navigation("Ilan");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniDeneyimSuresi", b =>
                {
                    b.HasOne("Kariyer.Entities.DeneyimSure", "DeneyimSure")
                        .WithMany()
                        .HasForeignKey("DeneyimSureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeneyimSure");

                    b.Navigation("Ilan");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniDurum", b =>
                {
                    b.HasOne("Kariyer.Entities.IlanDurumu", "IlanDurumu")
                        .WithMany()
                        .HasForeignKey("IlanDurumuId");

                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("IlanDurumu");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniMezuniyet", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Mezuniyet", "Mezuniyet")
                        .WithMany()
                        .HasForeignKey("MezuniyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Mezuniyet");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniSehir", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniSektor", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sektor", "Sektor")
                        .WithMany()
                        .HasForeignKey("SektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Sektor");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniUlke", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Ulke");
                });

            modelBuilder.Entity("Kariyer.Entities.IsIlaniYabanciDil", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.YabanciDil", "YabanciDil")
                        .WithMany()
                        .HasForeignKey("YabanciDilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("YabanciDil");
                });

            modelBuilder.Entity("Kariyer.Entities.MulakatListe", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", null)
                        .WithMany("MulakatListeleri")
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Mulakat", null)
                        .WithMany("MulakatListeleri")
                        .HasForeignKey("MulakatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ozgecmis", null)
                        .WithMany("MulakatListeleri")
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sirket", null)
                        .WithMany("MulakatListeleri")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.Ozgecmis", b =>
                {
                    b.HasOne("Kariyer.Entities.Cinsiyet", null)
                        .WithMany("Ozgecmisler")
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Ulke", null)
                        .WithMany("Ozgecmisler")
                        .HasForeignKey("UlkeId");

                    b.HasOne("Kariyer.Entities.Uyelik", null)
                        .WithMany("Ozgecmisler")
                        .HasForeignKey("UyelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisHavuzu", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", null)
                        .WithMany("OzgecmisHavuzlari")
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sirket", null)
                        .WithMany("OzgecmisHavuzlari")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisSehir", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", null)
                        .WithMany("OzgecmisSehirler")
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sehir", null)
                        .WithMany("OzgecmisSehirler")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisSosyalMedya", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.SosyalMedya", "SosyalMedya")
                        .WithMany()
                        .HasForeignKey("SosyalMedyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");

                    b.Navigation("SosyalMedya");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisYabanciDil", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.YabanciDil", "YabanciDil")
                        .WithMany()
                        .HasForeignKey("YabanciDilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");

                    b.Navigation("YabanciDil");
                });

            modelBuilder.Entity("Kariyer.Entities.OzgecmisYazilimDil", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", null)
                        .WithMany("OzgecmisYalizimDilleri")
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.YazilimDil", null)
                        .WithMany("OzgecmisYazilimDilleri")
                        .HasForeignKey("YazilimDilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.Referans", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.Sertifika", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.Sinav", b =>
                {
                    b.HasOne("Kariyer.Entities.Ozgecmis", "Ozgecmis")
                        .WithMany()
                        .HasForeignKey("OzgecmisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ozgecmis");
                });

            modelBuilder.Entity("Kariyer.Entities.Sirket", b =>
                {
                    b.HasOne("Kariyer.Entities.Uyelik", "Uyelik")
                        .WithMany()
                        .HasForeignKey("UyelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uyelik");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketIlan", b =>
                {
                    b.HasOne("Kariyer.Entities.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketSehir", b =>
                {
                    b.HasOne("Kariyer.Entities.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketSektor", b =>
                {
                    b.HasOne("Kariyer.Entities.Sektor", "Sektor")
                        .WithMany()
                        .HasForeignKey("SektorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sektor");

                    b.Navigation("Sirket");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketSosyalMedya", b =>
                {
                    b.HasOne("Kariyer.Entities.Sirket", "Sirket")
                        .WithMany()
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.SosyalMedya", "SosyalMedya")
                        .WithMany()
                        .HasForeignKey("SosyalMedyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sirket");

                    b.Navigation("SosyalMedya");
                });

            modelBuilder.Entity("Kariyer.Entities.SirketTakip", b =>
                {
                    b.HasOne("Kariyer.Entities.Sirket", null)
                        .WithMany("SirketTakipleri")
                        .HasForeignKey("SirketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kariyer.Entities.Uyelik", null)
                        .WithMany("SirketTakipleri")
                        .HasForeignKey("UyelikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kariyer.Entities.Uyelik", b =>
                {
                    b.HasOne("Kariyer.Entities.Rol", "Rol")
                        .WithMany("Uyelikler")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Kariyer.Entities.Bolum", b =>
                {
                    b.Navigation("Egitimler");
                });

            modelBuilder.Entity("Kariyer.Entities.Cinsiyet", b =>
                {
                    b.Navigation("Ozgecmisler");
                });

            modelBuilder.Entity("Kariyer.Entities.Fakulte", b =>
                {
                    b.Navigation("Bolumler");
                });

            modelBuilder.Entity("Kariyer.Entities.Ilan", b =>
                {
                    b.Navigation("MulakatListeleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Mulakat", b =>
                {
                    b.Navigation("MulakatListeleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Ozgecmis", b =>
                {
                    b.Navigation("Egitim");

                    b.Navigation("MulakatListeleri");

                    b.Navigation("OzgecmisHavuzlari");

                    b.Navigation("OzgecmisSehirler");

                    b.Navigation("OzgecmisYalizimDilleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Rol", b =>
                {
                    b.Navigation("Uyelikler");
                });

            modelBuilder.Entity("Kariyer.Entities.Sehir", b =>
                {
                    b.Navigation("OzgecmisSehirler");
                });

            modelBuilder.Entity("Kariyer.Entities.Sirket", b =>
                {
                    b.Navigation("MulakatListeleri");

                    b.Navigation("OzgecmisHavuzlari");

                    b.Navigation("SirketTakipleri");
                });

            modelBuilder.Entity("Kariyer.Entities.Ulke", b =>
                {
                    b.Navigation("Ozgecmisler");
                });

            modelBuilder.Entity("Kariyer.Entities.Universite", b =>
                {
                    b.Navigation("Fakulteler");
                });

            modelBuilder.Entity("Kariyer.Entities.Uyelik", b =>
                {
                    b.Navigation("Ozgecmisler");

                    b.Navigation("SirketTakipleri");
                });

            modelBuilder.Entity("Kariyer.Entities.YazilimDil", b =>
                {
                    b.Navigation("OzgecmisYazilimDilleri");
                });
#pragma warning restore 612, 618
        }
    }
}
